name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy-pages:
    name: Deploy Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: yarn install --network-timeout 86400000
      - name: Unit Test
        run: yarn test
      - name: Build Production
        run: yarn build
        env:
          BASE_URL: https://homapis.vercel.app/api
          NEXT_PUBLIC_BASE_URL: https://homapis.vercel.app/api
      - name: Export Static
        run: yarn export
        env:
          BASE_URL: https://homapis.vercel.app/api
          NEXT_PUBLIC_BASE_URL: https://homapis.vercel.app/api
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GHP_TOKEN }}
          branch: gh-pages
          folder: out
          clean: true
